accounts/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth.views import LogoutView
from .views import (
    UserSignInView,
    UserProfileView,
    UserSignUpView,
    UserPostCreationView,
    UserPostDeleteView
)

app_name = 'account'
urlpatterns = [
    path('signin/', UserSignInView.as_view(), name='signin'),
    path('signout/', LogoutView.as_view(), name='signout'),
    path('signup/', UserSignUpView.as_view(), name='signup'),

    path('profile/', UserProfileView.as_view(), name='profile'),
    path('post_create/', UserPostCreationView.as_view(), name='post_create'),
    path('post_delete/<int:pk>/', UserPostDeleteView.as_view(), name='post_delete'),

]

market/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('post/', include('posts.urls') ),
    path('account/', include('accounts.urls') ),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.contrib import admin
from django.urls import path
from .views import (
    PostsListView,
    PostDetailView,
    PostsCategoryListView
)

app_name = 'posts'
urlpatterns = [
    path('all/', PostsListView.as_view(), name='all-posts'),
    path('detail/<int:pk>', PostDetailView.as_view(), name='post-detail'),
    path('category/<slug:slug>', PostsCategoryListView.as_view(), name="category-posts"),
]

posts/models.py
from django.db import models
from django.conf import settings
from django.utils.text import slugify
from django.urls import reverse


# Create your models here.
STATUS_CHOICES = (
    ('draft', 'Draft'),
    ('published', 'Published'),
)


class Category(models.Model):
    title = models.CharField(max_length=50, verbose_name="title", null=True, blank=True,)
    slug = models.SlugField(max_length=50, verbose_name="slug", null=True, blank=True,)

    class Meta:
        verbose_name = "category"
        verbose_name_plural = "categories"

    def get_absolute_url(self):
        return reverse('posts:category-posts', kwargs={'slug': self.slug})

    def __str__(self) -> str:
        return self.title


class Post(models.Model):
    title = models.CharField(max_length=250, verbose_name="title", null=True, blank=True)
    slug = models.SlugField(max_length=250, verbose_name="slug", null=False, blank=False, unique=True, allow_unicode=True)
    body = models.TextField(verbose_name="body", null=True, blank=True)
    created_at = models.DateTimeField(verbose_name="created at", auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name="updated at", auto_now=True)
    image = models.ImageField(verbose_name="image", null=True, blank=True, upload_to="images")
    price = models.DecimalField(verbose_name="price", max_digits=10, decimal_places=0, null=True, blank=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')
    category = models.ManyToManyField(
        Category,
        verbose_name="category",
        related_name="posts", 
    )
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL, 
        verbose_name="author",
        on_delete=models.CASCADE,
    )
    
    class Meta:
        verbose_name = "post"
        verbose_name_plural = "posts"

    def get_absolute_url(self):
        return reverse('posts:post-detail', kwargs={'pk' : self.pk})

    def __str__(self) -> str:
        return self.title

    # def save(self, *args, **kwargs):
    #     self.slug = slugify(self.title, allow_unicode=True)
    #     return super().save(*args, **kwargs)

posts/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import (
    ListView,
    DetailView,
    CreateView
)
from .models import (
    Category,
    Post,
)


class PostsListView(ListView):
    template_name = "post/posts_list.html"
    context_object_name = 'posts'
    paginate_by = 5

    def get_queryset(self):
        list_of_posts = Post.objects.filter(status='published')
        return list_of_posts


class PostDetailView(DetailView):
    template_name = "post/post_detail.html"
    context_object_name = 'post'

    def get_object(self):
        post = get_object_or_404(Post, pk=self.kwargs['pk'])
        return post

    def get_context_data(self, **kwargs):
        """ here i get last 4 posts that have the same category with this post """

        context = super().get_context_data(**kwargs)
        post_categories = [category.id for category in context['object'].category.all()]
        related_posts = Post.objects.filter(category__id__in = post_categories).distinct()
        context['related_posts'] = related_posts[:4]
        return context


class PostsCategoryListView(ListView):
    template_name = "post/posts_category_list.html"
    context_object_name = 'posts'
    paginate_by = 5

    def get_queryset(self):
        category = get_object_or_404(Category, slug=self.kwargs['slug'])
        list_of_posts = category.posts.filter(status='published')
        return list_of_posts

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category'] = get_object_or_404(Category, slug=self.kwargs['slug'])
        return context



# class PostCreateView(LoginRequiredMixin,CreateView):
#     template_name = "post/post_create.html"
#     model = Post
#     fields = ['title', 'body', 'image', 'price', 'category']

#     def form_valid(self, form):
#         form.instance.author = self.request.user
#         return super().form_valid(form)

templates/post/base.html
{% load static %}

<!doctype html>
<html lang="fa">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %} {% endblock %}</title>
    <link rel="icon" href="{% static 'img/favicon.png' %}">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap4-rtl.min.css' %}">
    <!-- animate CSS -->
    <link rel="stylesheet" href="{% static 'css/animate.css' %}">
    <!-- owl carousel CSS -->
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <!-- font awesome CSS -->
    <link rel="stylesheet" href="{% static 'css/all.css' %}">
    <!-- flaticon CSS -->
    <link rel="stylesheet" href="{% static 'css/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'css/themify-icons.css' %}">
    <!-- font awesome CSS -->
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
    <!-- swiper CSS -->
    <link rel="stylesheet" href="{% static 'css/slick.css' %}">
    <!-- style CSS -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>

<body class="rtl">
    <!--::header part start::-->
    <header class="main_menu home_menu">
        <div class="container">
            <div class="row align-items-center justify-content-center">
                <div class="col-lg-12">
                    <nav class="navbar navbar-expand-lg navbar-light">
                        <a class="navbar-brand" href="index.html"> <img src="{% static 'img/logo.png' %}" alt="logo"> </a>
                        <button class="navbar-toggler" type="button" data-toggle="collapse"
                            data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                            <span class="menu_icon"><i class="fas fa-bars"></i></span>
                        </button>

                        <div class="collapse navbar-collapse main-menu-item" id="navbarSupportedContent">
                            <ul class="navbar-nav">
                                <li class="nav-item">
                                    <a class="nav-link" href="index.html">صفحه اصلی</a>
                                </li>
                                
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="blog.html" id="navbarDropdown_1"
                                        role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        دسته بندی ها
                                    </a>
                                    <div class="dropdown-menu" aria-labelledby="navbarDropdown_1">
                                        {% for category in categories_list %}
                                        <a class="dropdown-item" href="{{category.get_absolute_url}}">{{category.title}}</a>
                                        {% endfor %}
                                    </div>
                                </li>
                                {% if user.is_authenticated %}
                               <li class="nav-item">
                                    <a class="nav-link" href="{% url 'account:post_create' %}">افزودن آگهی</a>
                                </li>
                                {% endif %}
                                <li class="nav-item">
                                        {% if user.is_authenticated %}
                                        <a class="nav-link" href="{% url 'account:signout' %}">
                                            خروج
                                        </a>
                                        {% else %}
                                        <a class="nav-link" href="{% url 'account:signin' %}">
                                            ورود / ثبت نام
                                        </a>
                                        {% endif %}
                                    </a>
                                </li>

                            </ul>
                        </div>
                        <div class="hearer_icon d-flex align-items-center">
                            <a id="search_1" href="javascript:void(0)"><i class="ti-search"></i></a>
                            <a href="cart.html">
                                <i class="flaticon-shopping-cart-black-shape"></i>
                            </a>
                        </div>
                    </nav>
                </div>
            </div>
        </div>
        <div class="search_input" id="search_input_box">
            <div class="container ">
                <form class="d-flex justify-content-between search-inner">
                    <input type="text" class="form-control" id="search_input" placeholder="جست و جو">
                    <button type="submit" class="btn"></button>
                    <span class="ti-close" id="close_search" title="Close Search"></span>
                </form>
            </div>
        </div>
    </header>
    <!-- Header part end-->

    {% block content %}
    {% endblock %}


    
    <!--::footer_part start::-->
    <footer class="footer_part" style="clear: both;">
        <div class="footer_iner">
            <div class="container">
                <div class="row justify-content-between align-items-center">
                    <div class="col-lg-8">
                        <div class="footer_menu">
                            <div class="footer_logo">
                                <a href="index.html"><img src="{% static 'img/logo.png' %}" alt="#"></a>
                            </div>
                            <div class="footer_menu_item">
                                <a href="index.html">صفحه اصلی</a>

                                <a href="product_list.html">محصولات</a>
                                <a href="#">صفحات</a>
                                <a href="blog.html">وبلاگ</a>
                                <a href="contact.html">تماس با ما</a>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="social_icon">
                            <a href="#"><i class="fab fa-facebook-f"></i></a>
                            <a href="#"><i class="fab fa-instagram"></i></a>
                            <a href="#"><i class="fab fa-google-plus-g"></i></a>
                            <a href="#"><i class="fab fa-linkedin-in"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        
        <div class="copyright_part">
            <div class="container">
                <div class="row ">
                    <div class="col-lg-12">
                        <div class="copyright_text">
                            <P><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="ti-heart" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></P>
                            <p>فارسی و راست چین شده<i class="ti-heart" aria-hidden="true"></i> توسط <a
                                    href="https://webrubik.com/" target="-blank">Webrubik.com </a>- غزاله نظام
                            </p>
                            <div class="copyright_link">
                                <a href="#">ضوابط و شرایط</a>
                                <a href="#">FAQ</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
</footer>
<!--::footer_part end::-->

<!-- jquery plugins here-->
<script src="{% static 'js/jquery-1.12.1.min.js' %}"></script>
<!-- popper js -->
<script src="{% static 'js/popper.min.js' %}"></script>
<!-- bootstrap js -->
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<!-- easing js -->
<script src="{% static 'js/jquery.magnific-popup.js' %}"></script>
<!-- swiper js -->
<script src="{% static 'js/swiper.min.js' %}"></script>
<!-- swiper js -->
<script src="{% static 'js/mixitup.min.js' %}"></script>
<!-- particles js -->
<script src="{% static 'js/owl.carousel.min.js' %}"></script>
<script src="{% static 'js/jquery.nice-select.min.js' %}"></script>
<!-- slick js -->
<script src="{% static 'js/slick.min.js' %}"></script>
<script src="{% static 'js/jquery.counterup.min.js' %}"></script>
<script src="{% static 'js/waypoints.min.js' %}"></script>
<script src="{% static 'js/contact.js' %}"></script>
<script src="{% static 'js/jquery.ajaxchimp.min.js' %}"></script>
<script src="{% static 'js/jquery.form.js' %}"></script>
<script src="{% static 'js/jquery.validate.min.js' %}"></script>
<script src="{% static 'js/mail-script.js' %}"></script>
<!-- custom js -->
<script src="{% static 'js/custom.js' %}"></script>
</body>

</html>

templates/post/post_detail.html
{%  extends 'post/base.html'  %}
{% load static %}

{% block title %}
    جزییات محصول
{% endblock %}
{% block content %}
  
  <!-- breadcrumb part start-->
    <section class="breadcrumb_part single_product_breadcrumb">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="breadcrumb_iner">
                        <h2>صفحه داخلی محصول</h2>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- breadcrumb part end-->

  <!--================Single Product Area =================-->
  <div class="product_image_area">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-lg-12">
          <div class="product_img_slide owl-carousel" dir="ltr">
            
            <div class="single_product_img">
              <img src="{{post.image.url}}" alt="#" class="img-fluid">
            </div>
          </div>
        </div>
        <div class="col-lg-8">
          <div class="single_product_text text-center">
            <h3> {{post.title}} </h3>
            <p>
                {{post.body}}
            </p>
            <div class="card_area">
                <div class="product_count_area">
                    <p>{{post.price}} تومان</p>
                </div>
             
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <h3 style="text-align: center;">پست های مرتبط با دسته بندی</h3>
  {% for related in related_posts %}
  <div style="display:inline;     margin: 0 100px 0 100px; ">
    <a href="{{related.get_absolute_url}}">{{related.title}}</a>
    <img src="{{related.image.url}}" alt="" style="width:75px; height:75px">
  </div>
  {% endfor %}
    
 
  <!--================End Single Product Area =================-->
   <!-- subscribe part here -->
   <section class="subscribe_part section_padding">
      <div class="container">
          <div class="row justify-content-center">
              <div class="col-lg-8">
                  <div class="subscribe_part_content">
                      <h2>به روز رسانی و مطالب پیشرفته!</h2>
                      <p>ما سعی در ارائه محصولات با کیفیت تر و با دوام تر با توجه با استانداردهای روز جهان داریم .</p>
                      <div class="subscribe_form">
                          <input type="email" placeholder="ایمیل خود را وارد کنید">
                          <a href="#" class="btn_1">تایید پرداخت</a>
                      </div>
                  </div>
              </div>
          </div>
      </div>
  </section>
  <!-- subscribe part end -->
{% endblock %}

templates/post/posts_category_list.html
{%  extends 'post/base.html'  %}
{% load static %}

{% block title %}
{{category}}
{% endblock %}
{% block content %}
    <!-- breadcrumb part start-->
    <section class="breadcrumb_part">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="breadcrumb_iner">
                        <h2> {{category}} </h2>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- breadcrumb part end-->
    
    <!-- product list part start-->
    <section class="product_list section_padding">
        <div class="container">
            <div class="row">
                <div class="col-md-4">
                    <div class="product_sidebar">
                        <div class="single_sedebar">
                            <form action="#">
                                <input type="text" name="#" placeholder="جست و جو">
                                <i class="ti-search"></i>
                            </form>
                        </div>
                        <div class="single_sedebar">
                            <div class="select_option">
                                <div class="select_option_list">دسته ها <i class="right fas fa-caret-down"></i> </div>
                                <div class="select_option_dropdown">
                                    <p><a href="#">دسته 1</a></p>
                                    <p><a href="#">دسته 2</a></p>
                                    <p><a href="#">دسته 3</a></p>
                                    <p><a href="#">دسته 4</a></p>
                                </div>
                            </div>
                        </div>
                        <div class="single_sedebar">
                            <div class="select_option">
                                <div class="select_option_list">مدل <i class="right fas fa-caret-down"></i> </div>
                                <div class="select_option_dropdown">
                                    <p><a href="#">مدل 1</a></p>
                                    <p><a href="#">مدل 2</a></p>
                                    <p><a href="#">مدل 3</a></p>
                                    <p><a href="#">مدل 4</a></p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-8">
                    <div class="product_list">
                        <div class="row">
                            {% for post in posts %}
                            <div class="col-lg-6 col-sm-6">
                                <div class="single_product_item">
                                    <img src="{{ post.image.url }}" alt="#" class="img-fluid">
                                    <h3> <a href="{{ post.get_absolute_url }}"> {{ post.title }} </a> </h3>
                                    {% if post.price %}
                                        <p> قیمت : {{post.price}}  </p>
                                    {% else %}
                                        <p> قیمت : توافقی </p>
                                    {% endif %}
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- product list part end-->
    
    <!-- feature part here -->
    <section class="feature_part section_padding">
        <div class="container">
            <div class="row justify-content-between">
                <div class="col-lg-6">
                    <div class="feature_part_tittle">
                        <h3>با استفاده از مواد ارگانیک، محصولات استانداردی در اینجا تولید می شود.</h3>
                    </div>
                </div>
                <div class="col-lg-5">
                    <div class="feature_part_content">
                        <p>“شرکت ما با بهره گیری از استراتژی های مختلف و استفاده از مواد ارگانیک و طبیعی سعی در تولید محصولاتی با کیفیت و مطابق نیاز شما دارد.</p>
                    </div>
                </div>
            </div>
            <div class="row justify-content-center">
                <div class="col-lg-3 col-sm-6">
                    <div class="single_feature_part">
                        <img src="{% static 'img/icon/feature_icon_1.svg' %}" alt="#">
                        <h4>پشتیبانی کارت های اعتباری</h4>
                    </div>
                </div>
                <div class="col-lg-3 col-sm-6">
                    <div class="single_feature_part">
                        <img src="{% static 'img/icon/feature_icon_2.svg' %}" alt="#">
                        <h4>سفارش آنلاین</h4>
                    </div>
                </div>
                <div class="col-lg-3 col-sm-6">
                    <div class="single_feature_part">
                        <img src="{% static 'img/icon/feature_icon_3.svg' %}" alt="#">
                        <h4>تحویل رایگان</h4>
                    </div>
                </div>
                <div class="col-lg-3 col-sm-6">
                    <div class="single_feature_part">
                        <img src="{% static 'img/icon/feature_icon_4.svg' %}" alt="#">
                        <h4>محصولات همراه با جایزه</h4>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- feature part end -->

    <!-- subscribe part here -->
    <section class="subscribe_part section_padding">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-8">
                    <div class="subscribe_part_content">
                        <h2>به روز رسانی و مطالب پیشرفته!</h2>
                        <p>ما سعی در ارائه محصولات با کیفیت تر و با دوام تر با توجه با استانداردهای روز جهان داریم .</p>
                        <div class="subscribe_form">
                            <input type="email" placeholder="ایمیل خود را وارد کنید">
                            <a href="#" class="btn_1">تایید پرداخت</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- subscribe part end -->

    {% endblock %}

templates/post/posts_list.html
{%  extends 'post/base.html'  %}
{% load static %}

{% block title %}
    لیست آگهی ها
{% endblock %}
{% block content %}
    <!-- breadcrumb part start-->
    <section class="breadcrumb_part">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="breadcrumb_iner">
                        <h2>لیست آگهی ها</h2>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- breadcrumb part end-->
    
    <!-- product list part start-->
    <section class="product_list section_padding">
        <div class="container">
            <div class="row">
                <div class="col-md-4">
                    <div class="product_sidebar">
                        <div class="single_sedebar">
                            <form action="#">
                                <input type="text" name="#" placeholder="جست و جو">
                                <i class="ti-search"></i>
                            </form>
                        </div>
                        <div class="single_sedebar">
                            <div class="select_option">
                                <div class="select_option_list">دسته ها <i class="right fas fa-caret-down"></i> </div>
                                <div class="select_option_dropdown">
                                    <p><a href="#">دسته 1</a></p>
                                    <p><a href="#">دسته 2</a></p>
                                    <p><a href="#">دسته 3</a></p>
                                    <p><a href="#">دسته 4</a></p>
                                </div>
                            </div>
                        </div>
                        <div class="single_sedebar">
                            <div class="select_option">
                                <div class="select_option_list">مدل <i class="right fas fa-caret-down"></i> </div>
                                <div class="select_option_dropdown">
                                    <p><a href="#">مدل 1</a></p>
                                    <p><a href="#">مدل 2</a></p>
                                    <p><a href="#">مدل 3</a></p>
                                    <p><a href="#">مدل 4</a></p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-8">
                    <div class="product_list">
                        <div class="row">
                            {% for post in posts %}
                            <div class="col-lg-6 col-sm-6">
                                <div class="single_product_item">
                                    <img src="{{ post.image.url }}" alt="#" class="img-fluid">
                                    <h3> <a href="{{ post.get_absolute_url }}"> {{ post.title }} </a> </h3>
                                    {% if post.price %}
                                        <p> قیمت : {{post.price}}  </p>
                                    {% else %}
                                        <p> قیمت : توافقی </p>
                                    {% endif %}
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- product list part end-->
    
    <!-- feature part here -->
    <section class="feature_part section_padding">
        <div class="container">
            <div class="row justify-content-between">
                <div class="col-lg-6">
                    <div class="feature_part_tittle">
                        <h3>با استفاده از مواد ارگانیک، محصولات استانداردی در اینجا تولید می شود.</h3>
                    </div>
                </div>
                <div class="col-lg-5">
                    <div class="feature_part_content">
                        <p>“شرکت ما با بهره گیری از استراتژی های مختلف و استفاده از مواد ارگانیک و طبیعی سعی در تولید محصولاتی با کیفیت و مطابق نیاز شما دارد.</p>
                    </div>
                </div>
            </div>
            <div class="row justify-content-center">
                <div class="col-lg-3 col-sm-6">
                    <div class="single_feature_part">
                        <img src="{% static 'img/icon/feature_icon_1.svg' %}" alt="#">
                        <h4>پشتیبانی کارت های اعتباری</h4>
                    </div>
                </div>
                <div class="col-lg-3 col-sm-6">
                    <div class="single_feature_part">
                        <img src="{% static 'img/icon/feature_icon_2.svg' %}" alt="#">
                        <h4>سفارش آنلاین</h4>
                    </div>
                </div>
                <div class="col-lg-3 col-sm-6">
                    <div class="single_feature_part">
                        <img src="{% static 'img/icon/feature_icon_3.svg' %}" alt="#">
                        <h4>تحویل رایگان</h4>
                    </div>
                </div>
                <div class="col-lg-3 col-sm-6">
                    <div class="single_feature_part">
                        <img src="{% static 'img/icon/feature_icon_4.svg' %}" alt="#">
                        <h4>محصولات همراه با جایزه</h4>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- feature part end -->

    <!-- subscribe part here -->
    <section class="subscribe_part section_padding">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-8">
                    <div class="subscribe_part_content">
                        <h2>به روز رسانی و مطالب پیشرفته!</h2>
                        <p>ما سعی در ارائه محصولات با کیفیت تر و با دوام تر با توجه با استانداردهای روز جهان داریم .</p>
                        <div class="subscribe_form">
                            <input type="email" placeholder="ایمیل خود را وارد کنید">
                            <a href="#" class="btn_1">تایید پرداخت</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- subscribe part end -->

    {% endblock %}